### PR TITLE
feat: switch to webview plugins

### LINKED ISSUE #29: Rationale for using native implementation of WebView
Why did you choose to implement the WebView in native code on Android and iOS?

From my perspective there is no real advantage there. It would be better to use the **[flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview)** package which supports Android, iOS, macOS and the web. Windows and Linux support could be added using the **[desktop_webview_window](https://pub.dev/packages/desktop_webview_window)** package.

IMHO the main disadvantage of the current solution is the usage of the system's default browser. There you have no control over cookies (that is especially bad when you want to log out from 3rd party provider using the SDK) and you have no fullscreen mode. Even worse on iOS you have to confirm that you *really* want to open the Casdoor website on the first attempt.

If this appears useful to you I want to offer my help in migrating the SDK to use the packages mentioned above.

### PR DESCRIPTION
**Pull request by fischermario**
Update to the SDK to realize cross-platform support as discussed in #29

Note: this does not break the current API.

An update to the example will follow soon!

Fix: https://github.com/casdoor/casdoor-flutter-sdk/issues/29

### CODE REVIEW

**Comment by hsluoyz** [comment]
@fischermario the PR has error, plz fix: https://github.com/casdoor/casdoor-flutter-sdk/actions/runs/6525561445

image

**Comment by fischermario** [comment]
We need major version 6.x of the flutter_inappwebview package. Unfortunately this version is still a prerelease which is why the sdk build fails. I'm sorry - I was not aware of that. I will try to find a solution.

**Comment by fischermario** [comment]
@hsluoyz Please merge PR #34 asap because this is also a critical bugfix. Thank you!

**Pull request merged**
